# Generated by Django 3.1.7 on 2021-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('champion', models.IntegerField()),
                ('championName', models.CharField(max_length=30)),
                ('spell1', models.IntegerField()),
                ('spell2', models.IntegerField()),
                ('win', models.BooleanField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('goldEarned', models.IntegerField()),
                ('champLevel', models.IntegerField()),
                ('totalMinionsKilled', models.IntegerField()),
                ('item0', models.IntegerField()),
                ('item1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
