# Generated by Django 3.1.7 on 2021-09-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
    ]
