# Generated by Django 3.1.7 on 2021-09-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210906_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='totalDamageDealt',
            field=models.IntegerField(default=0),
        ),
    ]
