# Generated by Django 3.1.7 on 2021-09-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_matchold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchold',
            options={'verbose_name_plural': 'OldMatches'},
        ),
    ]
