# Generated by Django 3.2.6 on 2021-08-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
