# Generated by Django 3.2.6 on 2021-09-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210826_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('champion', models.IntegerField()),
                ('championName', models.CharField(max_length=30)),
                ('spell1', models.IntegerField()),
                ('spell2', models.IntegerField()),
                ('win', models.BooleanField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('goldEarned', models.IntegerField()),
                ('champLevel', models.IntegerField()),
                ('totalMinionsKilled', models.IntegerField()),
                ('item0', models.IntegerField()),
                ('item1', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Yo',
        ),
    ]
